[package]
name = "logger-info"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
http = "0.2.8"
ascii_converter = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[lib]
path = "src/lib.rs"
