name: kernel

on:
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-10
          components: rust-src
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Prereqs
        run: cargo install bpf-linker

      - name: Build
        env:
          CARGO_CFG_BPF_TARGET_ARCH: ${{ matrix.arch }}
        run: |
          cd src
          cargo build -Zbuild-std=core --target=bpfel-unknown-none
          cargo build -Zbuild-std=core --target=bpfeb-unknown-none