name: kernel

on:
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup
      run: |
        sudo apt-get install -y make clang llvm libelf-dev
        rustup install stable
        rustup toolchain install nightly --component rust-src
        cargo install bpf-linker
    - name: Test
      run: |
        ls
        cargo --help
